#!/bin/bash -l

# Load the require modules
module load ${PYTHON_MODULE}
[[ ${CUDA_MODULE} ]] && module load ${CUDA_MODULE}

# Set working directory to home directory
cd ${HOME}

# Start up the Jupyter Notebook Server
jupyter notebook --config="${CONFIG_FILE}"
